language: rust
rust:
  - 1.36.0
  - stable
  - beta
  - nightly
before_script:
  - rustup component add rustfmt
script:
  - cargo build --verbose --all
  - cargo fmt --all -- --check
os:
  - windows
  - osx
  - linux