[workspace]
members = [
    "skulpin-renderer",
    "skulpin-renderer-sdl2",
    "skulpin-renderer-winit",
    "skulpin-app-winit"
]

[package]
name = "skulpin"
version = "0.5.2"
authors = ["Philip Degarmo <aclysma@gmail.com>"]
edition = "2018"
description = "This crate provides an easy option for drawing hardware-accelerated 2D by combining Vulkan and Skia."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/aclysma/skulpin"
homepage = "https://github.com/aclysma/skulpin"
keywords = ["skia", "vulkan", "ash", "2d", "graphics"]
categories = ["graphics", "gui", "multimedia", "rendering", "visualization"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "shaders/*.frag",
    "shaders/*.vert",
    "shaders/*.spv",
    "LICENSE-APACHE",
    "LICENSE-MIT",
    "README.md"
]

# Minimum required rust version:
# rust="1.37"

# NOTE: See README.md for implications on how feature selection will affect build-time. As of this writing, binary
# builds of skia are available for ALL of the features or NONE of the features. Only selecting some of the features will
# require building skia from scratch, which will greatly increase build times
[features]
skia_shaper = ["skulpin-renderer/shaper"]
skia_svg = ["skulpin-renderer/svg"]
skia_textlayout = ["skulpin-renderer/textlayout"]
skia_complete = ["skulpin-renderer/complete"]

skulpin_winit = []
skulpin_sdl2 = []

default = ["skulpin_winit", "skulpin_sdl2", "skia_complete"]

[dependencies]
skulpin-renderer = { path = "skulpin-renderer" }
skulpin-renderer-sdl2 = { path = "skulpin-renderer-sdl2" }
skulpin-renderer-winit = { path = "skulpin-renderer-winit" }
skulpin-app-winit = { path = "skulpin-app-winit" }

log="0.4"

[dev-dependencies]
env_logger = "0.6"

nalgebra = "0.18"
ncollide2d = "0.20"
nphysics2d = "0.12"

# The skulpin-renderer-sdl2 crate doesn't specify any features, but downstream libraries can do so by including sdl2
# for themselves
sdl2 = { version = ">=0.33", features = ["bundled", "static-link"] }
